# Generated by Django 4.2.7 on 2023-12-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auximage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.CharField(default='shoe', max_length=100),
            preserve_default=False,
        ),
    ]
