# Generated by Django 4.2.7 on 2023-12-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='auximage',
        ),
        migrations.AddField(
            model_name='product',
            name='auximage1',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Extra Image1 (optional)'),
        ),
        migrations.AddField(
            model_name='product',
            name='auximage2',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Extra Image2 (optional)'),
        ),
        migrations.AddField(
            model_name='product',
            name='auximage3',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Extra Image3 (optional)'),
        ),
    ]
